fix: remove duplicate qti_display_kernel_headers definition to avoid Soong conflict
error: kernel/xiaomi/veux/techpack/display/Android.bp:34:1: module "qti_display_kernel_headers" already defined
       hardware/qcom-caf/common/Android.bp:16:1 <-- previous definition here